import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import FeatureTitle from "../components/FeatureTitle";
import React, {CSSProperties} from "react";
import {GridImageText, GridTextImage, DefaultBlock, TextPart, ImagePart} from '../components/introducingGrids';

import Link from "next/link";
import {A, Q} from "../components/QA";

const Home: NextPage = () => {
  const figmaUrl = 'https://www.figma.com/proto/GpsUQwmqHQuxoWx84hIXJW/%E3%83%97%E3%83%AD%E3%83%88%E3%82%BF%E3%82%A4%E3%83%97?node-id=6%3A9&scaling=scale-down&page-id=0%3A1&starting-point-node-id=6%3A9'
  return (
    <div>
      <Head>
        <title>Sphere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.header_wrapper}>
          <div>
            <h1>Sphere</h1>
            <span>Circle × Circle = Sphere!</span>
            <p>
              大学新入生のためのサークル探しアプリ
            </p>
          </div>
        </div>
      </header>

      <main className={styles.main}>

        <DefaultBlock style={{background: 'white'}} useScrollAnimation={true}>
          <div style={{textAlign: 'center', margin: '3em 0', fontSize: '1.3em', fontWeight: 200}}>
            <p>
              「どんなサークルを選べば良いのか分からない！」<br/>
              「サークルには入りたいけど見学に行く勇気は出ないよ！」
            </p>
            <p>
              <b><span style={{fontFamily: "'Urbanist', sans-serif"}}>Sphere</span></b> はそんな大学生のお手伝いをします
            </p>
          </div>
        </DefaultBlock>

        <div className={styles.circle_image_line}>
          <div style={{backgroundImage: 'url(/thumbnail.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/tennis.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/score.jpg)', backgroundSize: 'cover'}}/>
        </div>

        <DefaultBlock style={{background: 'white'}} useScrollAnimation={true}>
          <div>
            <FeatureTitle enTitle={'Features'} jaTitle={'特徴'}>
              Sphereは自分の趣味や嗜好からサークルを見つけることが出来る<br/>
              サークル情報特化型アプリです。
            </FeatureTitle>
            <p>
              あなたのサークル探しをお手伝いする 3 つの特徴！
            </p>
            <div>
              <ol className={styles.features_ol}>
                <li>1. <a href={'#circles'}>    <span className={styles.marker} >サークル一覧機能</span> </a></li>
                <li>2. <a href={'#scouts'}>     <span className={styles.marker} >スカウト機能</span> </a></li>
                <li>3. <a href={'#suggestions'}><span className={styles.marker} >サジェスト機能</span> </a></li>
              </ol>
            </div>
          </div>
        </DefaultBlock>

        <div className={styles.circle_image_line}>
          <div style={{backgroundImage: 'url(/tennis.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/score.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/thumbnail.jpg)', backgroundSize: 'cover'}}/>
        </div>

        <span id={'circles'}/>
        <GridTextImage style={{height: 'var(--block-height)'}} useScrollAnimation={true}>
          <TextPart>
            <div style={{margin: 'auto'}}>
              <FeatureTitle enTitle={'Circles'} jaTitle={'サークル一覧機能'}>
                あなたの大学のすべてのサークル情報が一目で！
              </FeatureTitle>
              <div>
                <p>
                  サークルごとの活動日や<br/>
                  熱量が一覧から一目で分かる！<br/>
                  気になるサークルがあったら、<br/>
                  詳細なプロフィール見てみよう！
                </p>
              </div>
            </div>
          </TextPart>
          <ImagePart>
            <img
              src={'/circles.png'}
              alt={'サークル一覧ページ'}
              style={{transform: 'translate(40px, 320px) scale(0.9)'}}
            />
          </ImagePart>
        </GridTextImage>

        <span id={'scouts'}/>
        <GridImageText style={{height: 'var(--block-height)', background: 'rgb(255,250,248)'}}
                       useScrollAnimation={true}>
          <TextPart>
            <FeatureTitle enTitle={'Scouts'} jaTitle={'スカウト機能'}>
              あなたに合ったサークルの新歓にご招待！？
            </FeatureTitle>
            <p>
              あなたのプロフィールを見た<br/>
              サークルの先輩から<br/>
              新歓のお誘いが届くかも！
            </p>
          </TextPart>
          <ImagePart>
            <img
              src={'/scout.png'}
              alt={'スカウト'}
              style={{transform: 'scale(0.8) translateY(270px)'}}
            />
          </ImagePart>
        </GridImageText>

        <span id={'suggestions'}/>
        <GridTextImage style={{height: 'var(--block-height)'}}
                       useScrollAnimation={true}>
          <TextPart>
            <FeatureTitle enTitle={'Suggestions'} jaTitle={'サジェスト機能'}>
              アプリがあなたにおすすめのサークルをピックアップ！
            </FeatureTitle>
            <p>
              サークル一覧のはじめにアンケート結果から<br/>
              厳選されたおすすめのサークルを掲載！
            </p>
          </TextPart>
          <ImagePart>
            <img
              src={'/glad.png'}
              alt={'喜ぶ男性'}
              style={{transform: 'scale(2.2) translate(-30px, -30px)'}}
            />
          </ImagePart>
        </GridTextImage>

        <div className={styles.circle_image_line}>
          <div style={{backgroundImage: 'url(/thumbnail.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/score.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/tennis.jpg)', backgroundSize: 'cover'}}/>
        </div>

        <DefaultBlock useScrollAnimation={true}>
          <FeatureTitle enTitle={'Try it now!'} jaTitle={'使ってみましょう！'}>
            {''}
          </FeatureTitle>
          <p>
            まずはあなたの大学のサークルを確認してみてください！
          </p>
          <p>
            <Link href={figmaUrl}>
              <a className={styles.button} target="_blank" rel="noopener">使ってみる</a>
            </Link>
          </p>
        </DefaultBlock>

        <div className={styles.circle_image_line}>
          <div style={{backgroundImage: 'url(/tennis.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/thumbnail.jpg)', backgroundSize: 'cover'}}/>
          <div style={{backgroundImage: 'url(/score.jpg)', backgroundSize: 'cover'}}/>
        </div>

        <DefaultBlock useScrollAnimation={true}>
          <FeatureTitle enTitle={'Q&A'} jaTitle={'よくある質問'}>
            {''}
          </FeatureTitle>

          <Q>
            怪しいサークルに登録情報が見られてしまう危険はありませんか？
          </Q>
          <A>
            ご安心ください！
            サークル側にアンケートの結果は見られてしまいますが、
            ニックネームはユーザーIDとして個人を特定できない形で表示されます。
            ですからメッセージを無視した場合でもサークルに知られることはありません。
          </A>

        </DefaultBlock>

        <footer className={styles.footer}>
          <DefaultBlock>
            <p>
              このランディングページは『ポストenPiT AiBiC 2022 夏合宿』にて作成された
              <strong>架空</strong>のサービスのものです。
            </p>
            <p style={{fontWeight: 100}}>
              &copy; 2022 チーム等差数列
            </p>
            <p style={{fontWeight: 100, fontSize: '0.7em'}}>
              Powered by ▲Vercel + Next.js and Framer Motion
            </p>
          </DefaultBlock>
        </footer>
      </main>
    </div>
  )
}

export default Home
